// 食物营养数据库 (每 100g)
// 字段：name(名称), kcal(热量), p(蛋白质g), c(碳水g), f(脂肪g), cat(分类), alias(检索别名)
window.FOOD_DB = [
  // ========= 主食 - 米面薯 =========
  { name: "白米饭(熟)", kcal: 130, p: 2.7, c: 28, f: 0.3, cat: "主食", alias: "mifan rice" },
  { name: "糙米饭(熟)", kcal: 111, p: 2.6, c: 23, f: 0.9, cat: "主食", alias: "caomi" },
  { name: "黑米饭(熟)", kcal: 102, p: 2.4, c: 23, f: 0.6, cat: "主食", alias: "heimi" },
  { name: "小米粥", kcal: 46, p: 1.4, c: 8.4, f: 0.7, cat: "主食", alias: "xiaomi" },
  { name: "白粥", kcal: 30, p: 0.6, c: 6, f: 0.1, cat: "主食", alias: "zhou" },
  { name: "八宝粥", kcal: 110, p: 3, c: 22, f: 1, cat: "主食", alias: "babao" },
  { name: "燕麦片(干)", kcal: 389, p: 17, c: 66, f: 7, cat: "主食", alias: "yanmai oat" },
  { name: "燕麦粥(熟)", kcal: 71, p: 2.5, c: 12, f: 1.5, cat: "主食", alias: "yanmaizhou" },
  { name: "玉米(熟)", kcal: 96, p: 3.5, c: 21, f: 1.5, cat: "主食", alias: "yumi corn" },
  { name: "红薯(熟)", kcal: 86, p: 1.6, c: 20, f: 0.1, cat: "主食", alias: "hongshu" },
  { name: "紫薯(熟)", kcal: 86, p: 1.6, c: 20, f: 0.1, cat: "主食", alias: "zishu" },
  { name: "土豆(熟)", kcal: 87, p: 1.9, c: 20, f: 0.1, cat: "主食", alias: "tudou potato" },
  { name: "山药(熟)", kcal: 56, p: 1.9, c: 12, f: 0.2, cat: "主食", alias: "shanyao" },
  { name: "馒头", kcal: 223, p: 7, c: 47, f: 1.1, cat: "主食", alias: "mantou" },
  { name: "花卷", kcal: 217, p: 6.4, c: 47, f: 1, cat: "主食", alias: "huajuan" },
  { name: "包子(猪肉)", kcal: 227, p: 9, c: 35, f: 6.2, cat: "主食", alias: "baozi" },
  { name: "包子(素菜)", kcal: 200, p: 6, c: 35, f: 4, cat: "主食", alias: "sucai baozi" },
  { name: "饺子(猪肉)", kcal: 240, p: 9, c: 30, f: 9, cat: "主食", alias: "jiaozi dumpling" },
  { name: "馄饨", kcal: 200, p: 8, c: 28, f: 6, cat: "主食", alias: "hundun" },
  { name: "烧麦", kcal: 250, p: 8, c: 30, f: 11, cat: "主食", alias: "shaomai" },
  { name: "油条", kcal: 388, p: 6.9, c: 51, f: 17.6, cat: "主食", alias: "youtiao" },
  { name: "煎饼果子", kcal: 220, p: 8, c: 30, f: 8, cat: "主食", alias: "jianbing" },
  { name: "肉夹馍", kcal: 280, p: 10, c: 35, f: 11, cat: "主食", alias: "roujiamo" },
  { name: "烧饼", kcal: 280, p: 7, c: 45, f: 9, cat: "主食", alias: "shaobing" },
  { name: "葱油饼", kcal: 320, p: 6, c: 40, f: 15, cat: "主食", alias: "congyoubing" },
  { name: "韭菜盒子", kcal: 230, p: 6, c: 30, f: 10, cat: "主食", alias: "jiucai hezi" },
  { name: "意大利面(熟)", kcal: 158, p: 5.8, c: 31, f: 0.9, cat: "主食", alias: "pasta yidalimian" },
  { name: "米粉(熟)", kcal: 110, p: 2, c: 24, f: 0.5, cat: "主食", alias: "mifen" },
  { name: "河粉(熟)", kcal: 110, p: 2, c: 25, f: 0.4, cat: "主食", alias: "hefen" },
  { name: "凉皮", kcal: 105, p: 2.5, c: 22, f: 0.5, cat: "主食", alias: "liangpi" },
  { name: "拉面", kcal: 137, p: 4.5, c: 27, f: 0.8, cat: "主食", alias: "lamian noodle" },
  { name: "牛肉面", kcal: 220, p: 12, c: 25, f: 8, cat: "主食", alias: "niuroumian" },
  { name: "兰州拉面", kcal: 230, p: 12, c: 35, f: 4, cat: "主食", alias: "lanzhou" },
  { name: "担担面", kcal: 300, p: 10, c: 40, f: 10, cat: "主食", alias: "dandanmian" },
  { name: "炒面", kcal: 200, p: 5, c: 30, f: 6, cat: "主食", alias: "chaomian" },
  { name: "蛋炒饭", kcal: 175, p: 4.5, c: 24, f: 6.5, cat: "主食", alias: "danchaofan" },
  { name: "扬州炒饭", kcal: 200, p: 6, c: 26, f: 7, cat: "主食", alias: "yangzhou chaofan" },
  { name: "寿司(三文鱼)", kcal: 130, p: 5, c: 20, f: 3, cat: "主食", alias: "sushi" },
  { name: "饭团", kcal: 170, p: 3.5, c: 35, f: 1, cat: "主食", alias: "fantuan" },
  { name: "全麦面包", kcal: 247, p: 13, c: 41, f: 3.4, cat: "主食", alias: "quanmai bread" },
  { name: "白面包", kcal: 265, p: 9, c: 49, f: 3.2, cat: "主食", alias: "bread" },
  { name: "法棍", kcal: 270, p: 9, c: 55, f: 1, cat: "主食", alias: "faguan baguette" },
  { name: "牛角包", kcal: 406, p: 8, c: 45, f: 21, cat: "主食", alias: "croissant niujiao" },
  { name: "吐司", kcal: 313, p: 9, c: 50, f: 9, cat: "主食", alias: "tusi toast" },
  { name: "贝果", kcal: 257, p: 10, c: 50, f: 1.5, cat: "主食", alias: "bagel beiguo" },

  // ========= 肉禽 =========
  { name: "鸡胸肉(熟)", kcal: 165, p: 31, c: 0, f: 3.6, cat: "肉禽", alias: "jixiongrou chicken breast" },
  { name: "鸡腿肉(去皮)", kcal: 170, p: 26, c: 0, f: 7, cat: "肉禽", alias: "jituirou" },
  { name: "鸡腿肉(带皮)", kcal: 209, p: 26, c: 0, f: 11, cat: "肉禽", alias: "jitui" },
  { name: "鸡翅(熟)", kcal: 203, p: 30, c: 0, f: 8, cat: "肉禽", alias: "jichi wing" },
  { name: "炸鸡腿", kcal: 268, p: 22, c: 8, f: 17, cat: "肉禽", alias: "zhajitui" },
  { name: "白切鸡", kcal: 200, p: 24, c: 0, f: 12, cat: "肉禽", alias: "baiqieji" },
  { name: "口水鸡", kcal: 220, p: 22, c: 3, f: 14, cat: "肉禽", alias: "koushuiji" },
  { name: "宫保鸡丁", kcal: 230, p: 15, c: 8, f: 16, cat: "肉禽", alias: "gongbao jiding" },
  { name: "辣子鸡", kcal: 280, p: 20, c: 8, f: 19, cat: "肉禽", alias: "laziji" },
  { name: "烤鸡腿", kcal: 240, p: 22, c: 0, f: 16, cat: "肉禽", alias: "kaojitui" },
  { name: "鸭胸", kcal: 132, p: 19, c: 0, f: 6, cat: "肉禽", alias: "yaxiong duck" },
  { name: "烤鸭", kcal: 240, p: 15, c: 0, f: 19, cat: "肉禽", alias: "kaoya" },
  { name: "鸭腿", kcal: 217, p: 19, c: 0, f: 15, cat: "肉禽", alias: "yatui" },
  { name: "猪里脊(熟)", kcal: 143, p: 27, c: 0, f: 3.5, cat: "肉禽", alias: "zhuliji" },
  { name: "猪五花(熟)", kcal: 518, p: 9, c: 0, f: 52, cat: "肉禽", alias: "wuhua" },
  { name: "瘦猪肉", kcal: 143, p: 22, c: 0, f: 6, cat: "肉禽", alias: "shouzhurou" },
  { name: "排骨(熟)", kcal: 270, p: 26, c: 0, f: 19, cat: "肉禽", alias: "paigu" },
  { name: "红烧肉", kcal: 380, p: 15, c: 5, f: 35, cat: "肉禽", alias: "hongshaorou" },
  { name: "回锅肉", kcal: 320, p: 15, c: 3, f: 28, cat: "肉禽", alias: "huiguorou" },
  { name: "糖醋里脊", kcal: 235, p: 15, c: 20, f: 12, cat: "肉禽", alias: "tangculiji" },
  { name: "鱼香肉丝", kcal: 200, p: 12, c: 10, f: 13, cat: "肉禽", alias: "yuxiang rousi" },
  { name: "京酱肉丝", kcal: 215, p: 14, c: 8, f: 15, cat: "肉禽", alias: "jingjiang" },
  { name: "瘦牛肉", kcal: 250, p: 26, c: 0, f: 15, cat: "肉禽", alias: "niurou beef" },
  { name: "牛排(熟)", kcal: 271, p: 26, c: 0, f: 18, cat: "肉禽", alias: "niupai steak" },
  { name: "西冷牛排", kcal: 270, p: 26, c: 0, f: 18, cat: "肉禽", alias: "xiling" },
  { name: "菲力牛排", kcal: 220, p: 25, c: 0, f: 12, cat: "肉禽", alias: "feili" },
  { name: "红烧牛肉", kcal: 240, p: 22, c: 3, f: 15, cat: "肉禽", alias: "hongshao niurou" },
  { name: "瘦羊肉", kcal: 203, p: 25, c: 0, f: 11, cat: "肉禽", alias: "yangrou lamb" },
  { name: "羊肉串", kcal: 280, p: 22, c: 2, f: 20, cat: "肉禽", alias: "yangrouchuan" },
  { name: "培根", kcal: 540, p: 37, c: 1.4, f: 42, cat: "肉禽", alias: "peigen bacon" },
  { name: "香肠", kcal: 300, p: 12, c: 3, f: 27, cat: "肉禽", alias: "xiangchang sausage" },
  { name: "火腿", kcal: 145, p: 21, c: 1.5, f: 6, cat: "肉禽", alias: "huotui ham" },
  { name: "腊肠", kcal: 500, p: 22, c: 3, f: 45, cat: "肉禽", alias: "lachang" },
  { name: "火腿肠", kcal: 212, p: 14, c: 15, f: 12, cat: "肉禽", alias: "huotuichang" },

  // ========= 蛋类 =========
  { name: "鸡蛋(全)", kcal: 155, p: 13, c: 1.1, f: 11, cat: "蛋类", alias: "jidan egg" },
  { name: "煮鸡蛋", kcal: 155, p: 13, c: 1.1, f: 11, cat: "蛋类", alias: "zhujidan" },
  { name: "煎蛋", kcal: 196, p: 14, c: 0.8, f: 15, cat: "蛋类", alias: "jiandan" },
  { name: "蛋清", kcal: 52, p: 11, c: 0.7, f: 0.2, cat: "蛋类", alias: "danqing" },
  { name: "蛋黄", kcal: 322, p: 16, c: 3.6, f: 27, cat: "蛋类", alias: "danhuang" },
  { name: "蒸蛋", kcal: 110, p: 10, c: 1.5, f: 7, cat: "蛋类", alias: "zhengdan" },
  { name: "茶叶蛋", kcal: 145, p: 12, c: 2, f: 10, cat: "蛋类", alias: "chayedan" },
  { name: "鸭蛋", kcal: 185, p: 13, c: 1.5, f: 14, cat: "蛋类", alias: "yadan" },
  { name: "咸鸭蛋", kcal: 200, p: 12, c: 3, f: 14, cat: "蛋类", alias: "xianyadan" },
  { name: "皮蛋", kcal: 171, p: 14, c: 4.5, f: 11, cat: "蛋类", alias: "pidan" },
  { name: "鹌鹑蛋", kcal: 159, p: 13, c: 0.5, f: 11, cat: "蛋类", alias: "anchundan" },

  // ========= 鱼海鲜 =========
  { name: "三文鱼", kcal: 208, p: 20, c: 0, f: 13, cat: "鱼海鲜", alias: "sanwenyu salmon" },
  { name: "鳕鱼", kcal: 82, p: 18, c: 0, f: 0.7, cat: "鱼海鲜", alias: "xueyu cod" },
  { name: "金枪鱼", kcal: 132, p: 28, c: 0, f: 1, cat: "鱼海鲜", alias: "jinqiangyu tuna" },
  { name: "鲈鱼", kcal: 100, p: 18, c: 0, f: 2, cat: "鱼海鲜", alias: "luyu" },
  { name: "草鱼", kcal: 113, p: 16, c: 0, f: 5, cat: "鱼海鲜", alias: "caoyu" },
  { name: "鲫鱼", kcal: 108, p: 17, c: 0, f: 3, cat: "鱼海鲜", alias: "jiyu" },
  { name: "带鱼", kcal: 127, p: 18, c: 0, f: 5, cat: "鱼海鲜", alias: "daiyu" },
  { name: "黄花鱼", kcal: 98, p: 17, c: 0, f: 3, cat: "鱼海鲜", alias: "huanghua" },
  { name: "罗非鱼", kcal: 96, p: 20, c: 0, f: 1.7, cat: "鱼海鲜", alias: "luofei" },
  { name: "红烧鱼", kcal: 200, p: 22, c: 3, f: 11, cat: "鱼海鲜", alias: "hongshaoyu" },
  { name: "清蒸鱼", kcal: 130, p: 22, c: 0, f: 4, cat: "鱼海鲜", alias: "qingzhengyu" },
  { name: "水煮鱼", kcal: 230, p: 22, c: 3, f: 14, cat: "鱼海鲜", alias: "shuizhuyu" },
  { name: "酸菜鱼", kcal: 180, p: 22, c: 3, f: 9, cat: "鱼海鲜", alias: "suancaiyu" },
  { name: "鱿鱼", kcal: 92, p: 15, c: 3, f: 1.4, cat: "鱼海鲜", alias: "youyu squid" },
  { name: "章鱼", kcal: 82, p: 15, c: 2, f: 1, cat: "鱼海鲜", alias: "zhangyu" },
  { name: "虾仁", kcal: 99, p: 24, c: 0, f: 0.3, cat: "鱼海鲜", alias: "xiaren shrimp" },
  { name: "大虾(熟)", kcal: 99, p: 24, c: 0, f: 0.3, cat: "鱼海鲜", alias: "daxia" },
  { name: "龙虾", kcal: 89, p: 19, c: 0, f: 0.9, cat: "鱼海鲜", alias: "longxia lobster" },
  { name: "螃蟹", kcal: 95, p: 19, c: 0, f: 1.5, cat: "鱼海鲜", alias: "pangxie crab" },
  { name: "蛤蜊", kcal: 86, p: 15, c: 3, f: 1, cat: "鱼海鲜", alias: "geli" },
  { name: "扇贝", kcal: 88, p: 17, c: 2.4, f: 0.8, cat: "鱼海鲜", alias: "shanbei" },
  { name: "生蚝", kcal: 81, p: 9, c: 4.7, f: 2.3, cat: "鱼海鲜", alias: "shenghao oyster" },
  { name: "麻辣小龙虾", kcal: 150, p: 22, c: 3, f: 5, cat: "鱼海鲜", alias: "xiaolongxia" },

  // ========= 豆制品 =========
  { name: "豆腐", kcal: 76, p: 8, c: 1.9, f: 4.8, cat: "豆制品", alias: "doufu tofu" },
  { name: "嫩豆腐", kcal: 56, p: 6, c: 1.5, f: 3, cat: "豆制品", alias: "nendoufu" },
  { name: "老豆腐", kcal: 117, p: 12, c: 3, f: 6.5, cat: "豆制品", alias: "laodoufu" },
  { name: "内酯豆腐", kcal: 49, p: 5, c: 1.5, f: 2.5, cat: "豆制品", alias: "neizhi doufu" },
  { name: "豆腐干", kcal: 142, p: 16, c: 4, f: 8, cat: "豆制品", alias: "doufugan" },
  { name: "豆皮", kcal: 489, p: 45, c: 16, f: 30, cat: "豆制品", alias: "doupi" },
  { name: "腐竹", kcal: 459, p: 45, c: 22, f: 22, cat: "豆制品", alias: "fuzhu" },
  { name: "豆浆", kcal: 31, p: 3.2, c: 2.4, f: 0.9, cat: "豆制品", alias: "doujiang" },
  { name: "豆腐脑", kcal: 47, p: 5, c: 1.5, f: 2.5, cat: "豆制品", alias: "doufunao" },
  { name: "麻婆豆腐", kcal: 200, p: 10, c: 8, f: 14, cat: "豆制品", alias: "mapo doufu" },
  { name: "家常豆腐", kcal: 180, p: 9, c: 8, f: 12, cat: "豆制品", alias: "jiachang doufu" },

  // ========= 乳制品 =========
  { name: "全脂牛奶", kcal: 60, p: 3.2, c: 4.8, f: 3.3, cat: "乳制品", alias: "niunai milk" },
  { name: "低脂牛奶", kcal: 42, p: 3.4, c: 5, f: 1, cat: "乳制品", alias: "difu niunai" },
  { name: "脱脂牛奶", kcal: 33, p: 3.4, c: 5, f: 0.1, cat: "乳制品", alias: "tuozhi" },
  { name: "酸奶(原味)", kcal: 59, p: 10, c: 3.6, f: 0.4, cat: "乳制品", alias: "suannai yogurt" },
  { name: "酸奶(全脂加糖)", kcal: 90, p: 5, c: 12, f: 3, cat: "乳制品", alias: "suannai" },
  { name: "希腊酸奶", kcal: 97, p: 10, c: 3.6, f: 5, cat: "乳制品", alias: "xila" },
  { name: "切达奶酪", kcal: 402, p: 25, c: 1.3, f: 33, cat: "乳制品", alias: "qieda cheese" },
  { name: "马苏里拉奶酪", kcal: 280, p: 22, c: 2.2, f: 22, cat: "乳制品", alias: "masulila mozzarella" },
  { name: "奶油", kcal: 345, p: 2.8, c: 3.5, f: 37, cat: "乳制品", alias: "naiyou cream" },
  { name: "黄油", kcal: 717, p: 0.9, c: 0.1, f: 81, cat: "乳制品", alias: "huangyou butter" },

  // ========= 蔬菜 =========
  { name: "西兰花", kcal: 34, p: 2.8, c: 7, f: 0.4, cat: "蔬菜", alias: "xilanhua broccoli" },
  { name: "菠菜", kcal: 23, p: 2.9, c: 3.6, f: 0.4, cat: "蔬菜", alias: "bocai spinach" },
  { name: "生菜", kcal: 15, p: 1.4, c: 2.9, f: 0.2, cat: "蔬菜", alias: "shengcai lettuce" },
  { name: "卷心菜", kcal: 25, p: 1.3, c: 5.8, f: 0.1, cat: "蔬菜", alias: "juanxincai cabbage" },
  { name: "紫甘蓝", kcal: 31, p: 1.4, c: 7.4, f: 0.2, cat: "蔬菜", alias: "ziganlan" },
  { name: "大白菜", kcal: 17, p: 1.5, c: 3.2, f: 0.2, cat: "蔬菜", alias: "baicai" },
  { name: "小白菜", kcal: 13, p: 1.5, c: 2.7, f: 0.3, cat: "蔬菜", alias: "xiaobaicai" },
  { name: "芹菜", kcal: 16, p: 0.7, c: 3, f: 0.2, cat: "蔬菜", alias: "qincai celery" },
  { name: "油菜", kcal: 23, p: 1.8, c: 2.7, f: 0.5, cat: "蔬菜", alias: "youcai" },
  { name: "韭菜", kcal: 26, p: 2.4, c: 4.6, f: 0.4, cat: "蔬菜", alias: "jiucai" },
  { name: "茼蒿", kcal: 23, p: 2.2, c: 3.2, f: 0.4, cat: "蔬菜", alias: "tonghao" },
  { name: "空心菜", kcal: 21, p: 2.5, c: 4, f: 0.2, cat: "蔬菜", alias: "kongxincai" },
  { name: "莴笋", kcal: 14, p: 1.4, c: 2.8, f: 0.1, cat: "蔬菜", alias: "wosun" },
  { name: "黄瓜", kcal: 16, p: 0.7, c: 3.6, f: 0.1, cat: "蔬菜", alias: "huanggua cucumber" },
  { name: "西红柿", kcal: 18, p: 0.9, c: 3.9, f: 0.2, cat: "蔬菜", alias: "xihongshi tomato" },
  { name: "圣女果", kcal: 18, p: 0.9, c: 3.9, f: 0.2, cat: "蔬菜", alias: "shengnvguo" },
  { name: "茄子", kcal: 25, p: 1, c: 6, f: 0.2, cat: "蔬菜", alias: "qiezi eggplant" },
  { name: "甜椒", kcal: 31, p: 1, c: 6, f: 0.3, cat: "蔬菜", alias: "tianjiao" },
  { name: "青椒", kcal: 20, p: 0.9, c: 4.6, f: 0.2, cat: "蔬菜", alias: "qingjiao pepper" },
  { name: "胡萝卜", kcal: 41, p: 0.9, c: 9.6, f: 0.2, cat: "蔬菜", alias: "huluobo carrot" },
  { name: "白萝卜", kcal: 18, p: 0.9, c: 4, f: 0.1, cat: "蔬菜", alias: "bailuobo" },
  { name: "洋葱", kcal: 40, p: 1.1, c: 9.3, f: 0.1, cat: "蔬菜", alias: "yangcong onion" },
  { name: "蒜薹", kcal: 60, p: 2, c: 13, f: 0.1, cat: "蔬菜", alias: "suantai" },
  { name: "大蒜", kcal: 149, p: 6.4, c: 33, f: 0.5, cat: "蔬菜", alias: "dasuan garlic" },
  { name: "蘑菇", kcal: 22, p: 3.1, c: 3.3, f: 0.3, cat: "蔬菜", alias: "mogu mushroom" },
  { name: "香菇", kcal: 34, p: 2.2, c: 7, f: 0.5, cat: "蔬菜", alias: "xianggu" },
  { name: "金针菇", kcal: 32, p: 2.4, c: 8, f: 0.3, cat: "蔬菜", alias: "jinzhengu" },
  { name: "平菇", kcal: 24, p: 2.2, c: 4, f: 0.3, cat: "蔬菜", alias: "pinggu" },
  { name: "木耳(湿)", kcal: 27, p: 1.5, c: 6, f: 0.2, cat: "蔬菜", alias: "muer" },
  { name: "竹笋", kcal: 27, p: 2.6, c: 5.2, f: 0.3, cat: "蔬菜", alias: "zhusun bamboo" },
  { name: "莲藕", kcal: 73, p: 1.9, c: 16, f: 0.1, cat: "蔬菜", alias: "lianou lotus" },
  { name: "南瓜", kcal: 26, p: 1, c: 6.5, f: 0.1, cat: "蔬菜", alias: "nangua pumpkin" },
  { name: "冬瓜", kcal: 12, p: 0.4, c: 2.6, f: 0.2, cat: "蔬菜", alias: "donggua" },
  { name: "苦瓜", kcal: 17, p: 1, c: 3.7, f: 0.2, cat: "蔬菜", alias: "kugua" },
  { name: "丝瓜", kcal: 20, p: 1, c: 4, f: 0.2, cat: "蔬菜", alias: "sigua" },
  { name: "豆角", kcal: 31, p: 1.8, c: 7, f: 0.1, cat: "蔬菜", alias: "doujiao bean" },
  { name: "豌豆", kcal: 81, p: 5.4, c: 14, f: 0.4, cat: "蔬菜", alias: "wandou pea" },
  { name: "毛豆", kcal: 122, p: 11, c: 9, f: 5, cat: "蔬菜", alias: "maodou edamame" },
  { name: "玉米粒", kcal: 86, p: 3.3, c: 19, f: 1.4, cat: "蔬菜", alias: "yumili" },
  { name: "海带", kcal: 12, p: 1.2, c: 2, f: 0.1, cat: "蔬菜", alias: "haidai" },
  { name: "紫菜", kcal: 207, p: 27, c: 45, f: 1, cat: "蔬菜", alias: "zicai nori" },
  { name: "西红柿炒蛋", kcal: 100, p: 5, c: 6, f: 6, cat: "菜肴", alias: "xihongshi chaodan" },
  { name: "地三鲜", kcal: 200, p: 3, c: 15, f: 15, cat: "菜肴", alias: "disanxian" },
  { name: "鱼香茄子", kcal: 200, p: 3, c: 15, f: 15, cat: "菜肴", alias: "yuxiang qiezi" },
  { name: "醋溜土豆丝", kcal: 100, p: 2, c: 15, f: 4, cat: "菜肴", alias: "culiu tudousi" },
  { name: "干煸豆角", kcal: 180, p: 4, c: 12, f: 13, cat: "菜肴", alias: "ganbian doujiao" },

  // ========= 水果 =========
  { name: "苹果", kcal: 52, p: 0.3, c: 14, f: 0.2, cat: "水果", alias: "pingguo apple" },
  { name: "香蕉", kcal: 89, p: 1.1, c: 23, f: 0.3, cat: "水果", alias: "xiangjiao banana" },
  { name: "橙子", kcal: 47, p: 0.9, c: 12, f: 0.1, cat: "水果", alias: "chengzi orange" },
  { name: "橘子", kcal: 53, p: 0.8, c: 13, f: 0.2, cat: "水果", alias: "juzi" },
  { name: "葡萄", kcal: 67, p: 0.6, c: 17, f: 0.4, cat: "水果", alias: "putao grape" },
  { name: "西瓜", kcal: 30, p: 0.6, c: 8, f: 0.2, cat: "水果", alias: "xigua watermelon" },
  { name: "哈密瓜", kcal: 34, p: 0.8, c: 8, f: 0.2, cat: "水果", alias: "hamigua" },
  { name: "草莓", kcal: 32, p: 0.7, c: 7.7, f: 0.3, cat: "水果", alias: "caomei strawberry" },
  { name: "蓝莓", kcal: 57, p: 0.7, c: 14, f: 0.3, cat: "水果", alias: "lanmei blueberry" },
  { name: "樱桃", kcal: 50, p: 1, c: 12, f: 0.3, cat: "水果", alias: "yingtao cherry" },
  { name: "桃子", kcal: 39, p: 0.9, c: 10, f: 0.3, cat: "水果", alias: "taozi peach" },
  { name: "李子", kcal: 46, p: 0.7, c: 11, f: 0.3, cat: "水果", alias: "lizi" },
  { name: "梨", kcal: 57, p: 0.4, c: 15, f: 0.1, cat: "水果", alias: "li pear" },
  { name: "菠萝", kcal: 50, p: 0.5, c: 13, f: 0.1, cat: "水果", alias: "boluo pineapple" },
  { name: "芒果", kcal: 60, p: 0.8, c: 15, f: 0.4, cat: "水果", alias: "mangguo mango" },
  { name: "木瓜", kcal: 43, p: 0.5, c: 11, f: 0.3, cat: "水果", alias: "mugua papaya" },
  { name: "火龙果", kcal: 60, p: 1.2, c: 13, f: 0.4, cat: "水果", alias: "huolongguo" },
  { name: "猕猴桃", kcal: 61, p: 1.1, c: 15, f: 0.5, cat: "水果", alias: "mihoutao kiwi" },
  { name: "牛油果", kcal: 160, p: 2, c: 9, f: 15, cat: "水果", alias: "niuyouguo avocado" },
  { name: "椰子", kcal: 354, p: 3.3, c: 15, f: 33, cat: "水果", alias: "yezi coconut" },
  { name: "榴莲", kcal: 147, p: 1.5, c: 27, f: 5, cat: "水果", alias: "liulian durian" },
  { name: "山竹", kcal: 73, p: 0.4, c: 18, f: 0.4, cat: "水果", alias: "shanzhu" },
  { name: "龙眼", kcal: 60, p: 1.3, c: 15, f: 0.1, cat: "水果", alias: "longyan longan" },
  { name: "荔枝", kcal: 66, p: 0.8, c: 17, f: 0.4, cat: "水果", alias: "lizhi lychee" },
  { name: "柚子", kcal: 38, p: 0.8, c: 10, f: 0.1, cat: "水果", alias: "youzi pomelo" },
  { name: "柠檬", kcal: 29, p: 1.1, c: 9, f: 0.3, cat: "水果", alias: "ningmeng lemon" },
  { name: "石榴", kcal: 83, p: 1.7, c: 19, f: 1.2, cat: "水果", alias: "shiliu pomegranate" },
  { name: "柿子", kcal: 81, p: 0.8, c: 22, f: 0.2, cat: "水果", alias: "shizi persimmon" },

  // ========= 坚果 =========
  { name: "杏仁", kcal: 579, p: 21, c: 22, f: 50, cat: "坚果", alias: "xingren almond" },
  { name: "花生", kcal: 567, p: 26, c: 16, f: 49, cat: "坚果", alias: "huasheng peanut" },
  { name: "核桃", kcal: 654, p: 15, c: 14, f: 65, cat: "坚果", alias: "hetao walnut" },
  { name: "腰果", kcal: 553, p: 18, c: 30, f: 44, cat: "坚果", alias: "yaoguo cashew" },
  { name: "开心果", kcal: 560, p: 20, c: 28, f: 45, cat: "坚果", alias: "kaixinguo pistachio" },
  { name: "榛子", kcal: 628, p: 15, c: 17, f: 61, cat: "坚果", alias: "zhenzi hazelnut" },
  { name: "松子", kcal: 673, p: 14, c: 13, f: 68, cat: "坚果", alias: "songzi pine" },
  { name: "葵花籽", kcal: 584, p: 21, c: 20, f: 51, cat: "坚果", alias: "kuihuazi sunflower" },
  { name: "南瓜子", kcal: 559, p: 30, c: 11, f: 49, cat: "坚果", alias: "nanguazi" },
  { name: "芝麻", kcal: 573, p: 18, c: 23, f: 50, cat: "坚果", alias: "zhima sesame" },
  { name: "板栗(熟)", kcal: 213, p: 3.4, c: 45, f: 2.3, cat: "坚果", alias: "banli chestnut" },

  // ========= 零食甜品 =========
  { name: "饼干(普通)", kcal: 480, p: 7, c: 65, f: 22, cat: "零食", alias: "binggan biscuit" },
  { name: "苏打饼干", kcal: 421, p: 9, c: 72, f: 10, cat: "零食", alias: "sudabinggan" },
  { name: "牛奶巧克力", kcal: 535, p: 8, c: 59, f: 30, cat: "零食", alias: "qiaokeli chocolate" },
  { name: "黑巧克力", kcal: 600, p: 7, c: 46, f: 43, cat: "零食", alias: "heiqiaokeli" },
  { name: "薯片", kcal: 547, p: 6.6, c: 53, f: 35, cat: "零食", alias: "shupian chips" },
  { name: "海绵蛋糕", kcal: 297, p: 5, c: 55, f: 8, cat: "零食", alias: "haimian dangao" },
  { name: "奶油蛋糕", kcal: 360, p: 4, c: 45, f: 19, cat: "零食", alias: "naiyou dangao" },
  { name: "提拉米苏", kcal: 240, p: 5, c: 30, f: 12, cat: "零食", alias: "tiramisu" },
  { name: "芝士蛋糕", kcal: 321, p: 5, c: 26, f: 22, cat: "零食", alias: "zhishi dangao" },
  { name: "戚风蛋糕", kcal: 280, p: 6, c: 40, f: 11, cat: "零食", alias: "qifeng" },
  { name: "蛋挞", kcal: 296, p: 5, c: 33, f: 16, cat: "零食", alias: "danta egg tart" },
  { name: "泡芙", kcal: 320, p: 7, c: 30, f: 19, cat: "零食", alias: "paofu puff" },
  { name: "甜甜圈", kcal: 452, p: 5, c: 51, f: 25, cat: "零食", alias: "tiantianquan donut" },
  { name: "月饼", kcal: 405, p: 7, c: 55, f: 18, cat: "零食", alias: "yuebing mooncake" },
  { name: "粽子(肉)", kcal: 200, p: 6, c: 30, f: 7, cat: "零食", alias: "zongzi" },
  { name: "汤圆", kcal: 290, p: 6, c: 45, f: 10, cat: "零食", alias: "tangyuan" },
  { name: "冰淇淋", kcal: 207, p: 3.5, c: 24, f: 11, cat: "零食", alias: "bingqilin icecream" },
  { name: "雪糕", kcal: 200, p: 3, c: 22, f: 12, cat: "零食", alias: "xuegao" },
  { name: "果冻", kcal: 80, p: 1, c: 18, f: 0, cat: "零食", alias: "guodong jelly" },
  { name: "棉花糖", kcal: 318, p: 2, c: 81, f: 0.2, cat: "零食", alias: "mianhuatang marshmallow" },

  // ========= 饮料 =========
  { name: "可乐", kcal: 42, p: 0, c: 10.6, f: 0, cat: "饮料", alias: "kele cola" },
  { name: "雪碧", kcal: 38, p: 0, c: 9.6, f: 0, cat: "饮料", alias: "xuebi sprite" },
  { name: "橙汁", kcal: 45, p: 0.7, c: 10, f: 0.2, cat: "饮料", alias: "chengzhi" },
  { name: "苹果汁", kcal: 46, p: 0.1, c: 11, f: 0.1, cat: "饮料", alias: "pingguozhi" },
  { name: "椰子水", kcal: 19, p: 0.7, c: 3.7, f: 0.2, cat: "饮料", alias: "yezishui" },
  { name: "红茶(无糖)", kcal: 1, p: 0, c: 0.3, f: 0, cat: "饮料", alias: "hongcha" },
  { name: "绿茶(无糖)", kcal: 1, p: 0, c: 0.3, f: 0, cat: "饮料", alias: "lvcha tea" },
  { name: "奶茶(全糖)", kcal: 80, p: 2, c: 14, f: 2, cat: "饮料", alias: "naicha milktea" },
  { name: "珍珠奶茶", kcal: 110, p: 2, c: 18, f: 3.5, cat: "饮料", alias: "zhenzhu naicha bubbletea" },
  { name: "美式咖啡", kcal: 5, p: 0.3, c: 0, f: 0.1, cat: "饮料", alias: "meishi kafei coffee" },
  { name: "拿铁", kcal: 65, p: 3.3, c: 6, f: 2.5, cat: "饮料", alias: "natie latte" },
  { name: "卡布奇诺", kcal: 60, p: 3.2, c: 5.5, f: 2.4, cat: "饮料", alias: "kabuqinuo cappuccino" },
  { name: "摩卡", kcal: 90, p: 3.5, c: 12, f: 3.5, cat: "饮料", alias: "moka mocha" },
  { name: "焦糖玛奇朵", kcal: 100, p: 3, c: 15, f: 3.5, cat: "饮料", alias: "jiaotang" },
  { name: "啤酒", kcal: 43, p: 0.5, c: 3.6, f: 0, cat: "饮料", alias: "pijiu beer" },
  { name: "红酒", kcal: 85, p: 0.1, c: 2.6, f: 0, cat: "饮料", alias: "hongjiu wine" },
  { name: "白酒(40度)", kcal: 235, p: 0, c: 0, f: 0, cat: "饮料", alias: "baijiu" },
  { name: "运动饮料", kcal: 30, p: 0, c: 7, f: 0, cat: "饮料", alias: "yundong" },

  // ========= 汤类 =========
  { name: "紫菜蛋花汤", kcal: 30, p: 3, c: 2, f: 1, cat: "汤", alias: "zicai danhuatang" },
  { name: "西红柿蛋汤", kcal: 40, p: 2.5, c: 3, f: 2, cat: "汤", alias: "xihongshi dantang" },
  { name: "鸡汤", kcal: 50, p: 4, c: 0.5, f: 4, cat: "汤", alias: "jitang" },
  { name: "排骨汤", kcal: 60, p: 4, c: 0.5, f: 5, cat: "汤", alias: "paigutang" },
  { name: "牛肉汤", kcal: 50, p: 5, c: 0.5, f: 3, cat: "汤", alias: "niuroutang" },
  { name: "玉米汤", kcal: 60, p: 2, c: 12, f: 0.5, cat: "汤", alias: "yumitang" },
  { name: "蘑菇汤", kcal: 30, p: 2, c: 4, f: 0.5, cat: "汤", alias: "mogutang" },
  { name: "罗宋汤", kcal: 60, p: 3, c: 8, f: 2, cat: "汤", alias: "luosongtang" },
  { name: "酸辣汤", kcal: 50, p: 3, c: 6, f: 2, cat: "汤", alias: "suanlatang" },
  { name: "味噌汤", kcal: 35, p: 2.5, c: 3, f: 1, cat: "汤", alias: "weizengtang miso" },

  // ========= 快餐西餐 =========
  { name: "牛肉汉堡", kcal: 295, p: 17, c: 30, f: 13, cat: "快餐", alias: "niurou hanbao burger" },
  { name: "起司汉堡", kcal: 303, p: 15, c: 30, f: 15, cat: "快餐", alias: "qisi" },
  { name: "鸡腿堡", kcal: 270, p: 12, c: 28, f: 13, cat: "快餐", alias: "jituibao" },
  { name: "巨无霸", kcal: 257, p: 12, c: 22, f: 14, cat: "快餐", alias: "juwuba bigmac" },
  { name: "玛格丽特披萨", kcal: 266, p: 11, c: 33, f: 10, cat: "快餐", alias: "pisa pizza" },
  { name: "培根披萨", kcal: 280, p: 12, c: 30, f: 13, cat: "快餐", alias: "peigen pisa" },
  { name: "炸薯条", kcal: 312, p: 3.4, c: 41, f: 15, cat: "快餐", alias: "shutiao fries" },
  { name: "炸鸡块", kcal: 290, p: 16, c: 16, f: 17, cat: "快餐", alias: "zhajikuai nugget" },
  { name: "三明治(火腿)", kcal: 250, p: 12, c: 26, f: 10, cat: "快餐", alias: "sanmingzhi sandwich" },
  { name: "卷饼", kcal: 200, p: 6, c: 30, f: 6, cat: "快餐", alias: "juanbing wrap" },
  { name: "肉酱意面", kcal: 158, p: 6, c: 22, f: 5, cat: "快餐", alias: "rouchang yimian bolognese" },
  { name: "奶油培根意面", kcal: 280, p: 8, c: 30, f: 14, cat: "快餐", alias: "carbonara" },
  { name: "千层面", kcal: 196, p: 11, c: 19, f: 8, cat: "快餐", alias: "qiancengmian lasagna" },
  { name: "焗饭", kcal: 200, p: 6, c: 22, f: 9, cat: "快餐", alias: "jufan" },
  { name: "凯撒沙拉", kcal: 180, p: 5, c: 8, f: 14, cat: "快餐", alias: "kaisa salad" },
  { name: "鸡肉沙拉", kcal: 130, p: 15, c: 5, f: 5, cat: "快餐", alias: "jirou sala" }
];
